workspace(name = "BazelVersion")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# Bazel version
git_repository(
    name = "build_bazel_rules_nodejs",
    #tag = "0.28.0",
    commit = "f18986bce027355bbb9724bddd279bb710ae16bb",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    shallow_since = "1556214188 -0700",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "check_bazel_version")

check_bazel_version("0.27.0")
