#
#   SPDX-FileCopyrightText: 2022 Julian Amann <dev@vertexwahn.de>
#   SPDX-License-Identifier: Apache-2.0
#


jobs:
  - job: Ubuntu20GCC9
    displayName: "GCC9 on Ubuntu 20.04"
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: ci/ubuntu-20.04-gcc9.yaml

jobs:
  - job: Ubuntu22GCC11
    displayName: "GCC11 on Ubuntu 22.04"
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
      - template: ci/ubuntu-22.04-gcc11.yaml
  