name: Update Vulkan SDK Versions

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run version update script
        run: python3 tools/update_versions.py
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet vulkan/private/versions.bzl; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in versions.bzl"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in versions.bzl"
          fi
      
      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          # Get latest Vulkan version from updated file
          LATEST_VERSION=$(grep 'LATEST_VERSION = ' vulkan/private/versions.bzl | sed 's/LATEST_VERSION = "\(.*\)"/\1/')
          
          # Configure git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Create branch name
          BRANCH_NAME="update-vulkan-${LATEST_VERSION}"
          
          # Check if branch already exists on remote
          if git ls-remote --exit-code --heads origin "$BRANCH_NAME" >/dev/null 2>&1; then
            echo "Branch $BRANCH_NAME already exists. Skipping PR creation."
            exit 0
          fi
          
          # Create branch
          git checkout -b "$BRANCH_NAME"
          
          # Get diff for PR body
          DIFF=$(git diff vulkan/private/versions.bzl)
          
          # Commit changes
          git add vulkan/private/versions.bzl
          git commit -m "Update Vulkan SDK versions to ${LATEST_VERSION}
          
          Automated update of available Vulkan SDK versions from LunarG."
          
          # Push branch
          git push origin "$BRANCH_NAME"
          
          # Create PR
          gh pr create \
            --title "Update Vulkan SDK versions to ${LATEST_VERSION}" \
            --label "sdk" \
            --body "$(cat <<EOF
          ## Summary
          - Updated available Vulkan SDK versions from LunarG website
          - Latest version: ${LATEST_VERSION}
          
          ## Changes
          \`\`\`diff
          ${DIFF}
          \`\`\`
          EOF
          )"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}