[tool.poetry]
name = "mitsuba-demo"
version = "0.1.0"
description = ""
authors = ["Julian Amann <dev@vertexwahn.de>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10.0"
mitsuba = "^3.2.0"
numpy = "^1.24.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
